CC=gcc
CFLAGS=-g -Wall

v1: clean input_to_output_v1.c
	$(CC) $(CFLAGS) input_to_output_v1.c -o input_to_output

v2: clean input_to_output_v2.c
	$(CC) $(CFLAGS) input_to_output_v2.c -o input_to_output

clean:
	$(RM) input_to_output
